kind: Service
apiVersion: v1
metadata:
  name: webui
  labels:
    app: webui
spec:
  ports:
    - name: 8000-tcp
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
  sessionAffinity: None
  selector:
    deployment: webui
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: webui
  labels:
    app.kubernetes.io/component: http
    app.kubernetes.io/instance: webui
    app.kubernetes.io/name: webui
    release: webui
spec:
  to:
    kind: Service
    name: webui
    weight: 100
  port:
    targetPort: 8000-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
